name: Run Tests and Upload Logs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Run Tests and Save Logs
        run: |
          mkdir -p ./Logs/toto-combine
          LOG_FILE="./Logs/toto-combine/test-log-$(date +%Y-%m-%d_%H-%M-%S).log"
          echo "🧪 Starting Tests at $(date)" > "$LOG_FILE"
          xcodebuild test \
            -scheme toto-combine \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            >> "$LOG_FILE" 2>&1
          echo "✅ Finished Tests at $(date)" >> "$LOG_FILE"

      - name: Upload Log Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: Logs/toto-combine/*.log
